apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: onlinegame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: onlinegame_auth
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "pg_isready -U postgres -d postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "pg_isready -U postgres -d postgres"]
            initialDelaySeconds: 15
            periodSeconds: 10