apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: onlinegame
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  ConnectionStrings__InventoryDb: Host=inventory-db;Port=5432;Database=onlinegame_inventory;Username=postgres;Password=postgres
