apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: onlinegame
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - name: http
      appProtocol: http
      port: 8080
      targetPort: 8080
    - name: grpc
      appProtocol: grpc
      port: 8081
      targetPort: 8081
