apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service
  namespace: onlinegame
spec:
  type: ClusterIP
  selector:
    app: matchmaking-service
  ports:
    - port: 8080
      targetPort: 8080
