apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-service
  namespace: onlinegame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking-service
  template:
    metadata:
      labels:
        app: matchmaking-service
    spec:
      containers:
        - name: matchmaking-service
          image: onlinegame/matchmaking-service:baseline
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: matchmaking-service-config
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
